// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEPeAiO0FvpvxU5W_n9-MuVJ5pK_VlysQ',
    appId: '1:463633781144:web:658b98e8d2e70e2edd5bed',
    messagingSenderId: '463633781144',
    projectId: 'examapp-6415c',
    authDomain: 'examapp-6415c.firebaseapp.com',
    storageBucket: 'examapp-6415c.appspot.com',
    measurementId: 'G-D0RRW1SDVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChYUgDrffx1HgDvl2zgQCCRxa5yMcOiLY',
    appId: '1:463633781144:android:6f6d97a48dd62013dd5bed',
    messagingSenderId: '463633781144',
    projectId: 'examapp-6415c',
    storageBucket: 'examapp-6415c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq-wKG3mvOSuTqKYY4uGRO013FayOFljo',
    appId: '1:463633781144:ios:bf92a04493c23daddd5bed',
    messagingSenderId: '463633781144',
    projectId: 'examapp-6415c',
    storageBucket: 'examapp-6415c.appspot.com',
    iosBundleId: 'com.example.examApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq-wKG3mvOSuTqKYY4uGRO013FayOFljo',
    appId: '1:463633781144:ios:bf92a04493c23daddd5bed',
    messagingSenderId: '463633781144',
    projectId: 'examapp-6415c',
    storageBucket: 'examapp-6415c.appspot.com',
    iosBundleId: 'com.example.examApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEPeAiO0FvpvxU5W_n9-MuVJ5pK_VlysQ',
    appId: '1:463633781144:web:255b9b0b70c3f946dd5bed',
    messagingSenderId: '463633781144',
    projectId: 'examapp-6415c',
    authDomain: 'examapp-6415c.firebaseapp.com',
    storageBucket: 'examapp-6415c.appspot.com',
    measurementId: 'G-QR4X2H4ZV5',
  );
}
